package intem.smartpos.utilities;

public class functions_db
{
    public static final String CreateSales = "CREATE TABLE Sales (id INTEGER PRIMARY KEY AUTOINCREMENT,Consecutive INTEGER,Client TEXT,Date TEXT,Status TEXT,Export INTEGER,Import INTEGER,Corte INTEGER,Credit INTEGER,DebtId INTEGER,PayMethod TEXT,ImportPay REAL,Observ TEXT)";
    public static final String CreateSalesParts = "CREATE TABLE SalesParts (id INTEGER PRIMARY KEY AUTOINCREMENT,SaleID INTEGER,ProdCode TEXT,ProdDescrip TEXT,Qty REAL,Price Real,PriceList INTEGER,Discount REAL,PrCode TEXT,PrDescrip TEXT,PrQty REAL,PrPrice REAL,weight Real)";
    public static final String CreateProviders = "CREATE TABLE Providers (id INTEGER PRIMARY KEY AUTOINCREMENT,ProviderCode TEXT,ProviderName TEXT)";
    public static final String CreatePurchases = "CREATE TABLE Purchases (id INTEGER PRIMARY KEY AUTOINCREMENT,Provider TEXT,Amount REAL,Date TEXT,Document TEXT,Status TEXT,Export INTEGER,ServerDetail TEXT)";
    public static final String CreatePurchasePart = "CREATE TABLE PurchasesPart (id INTEGER PRIMARY KEY AUTOINCREMENT,PurchaseId INTEGER,Prod TEXT,Qty REAL,DescripProd TEXT,Price REAL,Discount TEXT,Tax TEXT)";
    public static final String CreateCortes = "CREATE TABLE Cortes (id INTEGER PRIMARY KEY AUTOINCREMENT,Consecutive INTEGER,Content TEXT,Date TEXT,TotalSales REAL,Expenses REAL,User TEXT,OtherIncomes REAL,RecoveryDebt REAL,Estacion TEXT,Android INTEGER)";
    public static final String CreateUsers = "CREATE TABLE Users (id INTEGER PRIMARY KEY AUTOINCREMENT,Nick TEXT,Name TEXT,Password TEXT,Level TEXT,OrdersAccess INTEGER,MovsAccess INTEGER,ProdsAccess INTEGER,PurchasesAccess INTEGER,Clients INTEGER,POS INTEGER,Loged INTEGER,Discount INTEGER,PricesList INTEGER,SelectPriceWindow INTEGER)";
    public static final String CreateProds = "CREATE TABLE Prods (id INTEGER PRIMARY KEY AUTOINCREMENT,Code TEXT,Description TEXT,ProdCategory TEXT,Brand TEXT,Tax TEXT,Cost REAL,Price1 REAL,Price2 REAL,Price3 REAL,Price4 REAL,Price5 REAL,Price6 REAL,Price7 REAL,Price8 REAL,Price9 REAL,Qty2 INTEGER,Qty3 INTEGER,Qty4 INTEGER,Qty5 INTEGER,Qty6 INTEGER,Qty7 INTEGER,Qty8 INTEGER,Qty9 INTEGER,Exist INTEGER,ExSucursal TEXT,Export INTEGER,Offer Real,image TEXT)";
    public static final String CreatePresentations = "CREATE TABLE Presentations (id INTEGER PRIMARY KEY AUTOINCREMENT,CodePr TEXT,CodeProd TEXT,DescPr TEXT,QtyPr Real,PricePr REAL)";
    public static final String CreateClients = "CREATE TABLE Clients (id INTEGER PRIMARY KEY AUTOINCREMENT,CodeMyBusiness TEXT,Name TEXT,Export INTEGER,Street TEXT,Colony TEXT, City TEXT,CP TEXT,RFC TEXT,Email TEXT,Debt REAL)";
    public static final String CreateCredit = "CREATE TABLE Credit (id INTEGER PRIMARY KEY AUTOINCREMENT,Client TEXT,amount REAL,date TEXT,Location TEXT,Status TEXT,Aplicated TEXT,User TEXT)";
    public static final String CreateOrders = "CREATE TABLE Orders (id INTEGER PRIMARY KEY AUTOINCREMENT,Client TEXT,Date TEXT,Amount REAl,Location TEXT,Status TEXT,IdInServer INTEGER,ConsecInServer INTEGER,Observations TEXT,Export INTEGER)";
    public static final String CreatePartOrders = "CREATE TABLE PartOrders (id INTEGER PRIMARY KEY AUTOINCREMENT,OrderId INTEGER,Quantity REAL,ProdId TEXT,Price REAL,Descrip TEXT,Observations TEXT,PresentationClave TEXT,PresentationQty REAL,PresentationDescrip TEXT,PresentationPrice REAL,Export INTEGER,Discount REAL)";
    public static final String CreateMovsInv = "CREATE TABLE MovsInv (id INTEGER PRIMARY KEY AUTOINCREMENT,TypeMov String,DateMov String,IdInServer INTEGER,Folio INTEGER,User String)";
    public static final String CreatePartMovsInv = "CREATE TABLE PartMovsInv (id INTEGER PRIMARY KEY AUTOINCREMENT,MovId INTEGER,Quantity REAL,CodeProd TEXT,Descrip TEXT,Export INTEGER)";
    public static final String CreateAppConfig = "CREATE TABLE AppConfig (Enterprise TEXT,Adress TEXT,Phone TEXT,Terminal Text,Seller TEXT,ServerIP TEXT,EmailOrders TEXT,OnlyExist INTEGER,ImportSucEx INTEGER,SendProds INTEGER,DataSize INTEGER,LogoPath TEXT,InvFisInstant INTEGER,ReportingDateIn TEXT,ReportingDateFn TEXT,PendingSale INTEGER,Warehouse INTEGER,PricesByClient INTEGER,PriceQty INTEGER,PrEnabled INTEGER,InitialSetup INTEGER,Remision INTEGER,PrintTkSale INTEGER,PrintTkOrder INTEGER,OnlyUpdateProds INTEGER,OnlyUpdateClients INTEGER,DeleteOldData INTEGER)";
    public static final String CreateAdditionalProductReportingData  = "CREATE TABLE AdditionalProductReportingData (id INTEGER PRIMARY KEY AUTOINCREMENT,ProductCode TEXT,Family TEXT,SubFam1 TEXT,SubFam2 TEXT,SubFam3 TEXT,TotalPurchases TEXT,LastPurchaseDate TEXT,LastPurchasePrice TEXT,TotalSales REAL,AverageSales REAL,MainSupplier TEXT)";
    public static final String CreateConnections = "CREATE TABLE Connections (id INTEGER PRIMARY KEY AUTOINCREMENT,NameConnection TEXT,StringConn TEXT,Observ TEXT)";
    public static final String InsertConfig = "INSERT INTO AppConfig (Enterprise,Terminal,Seller,ServerIP,EmailOrders,OnlyExist,ImportSucEx,SendProds,DataSize,PriceQty,InvFisInstant,PendingSale,Warehouse,InitialSetup,OnlyUpdateProds,OnlyUpdateClients,DeleteOldData) values ('Empresa de Pruebas SA de CV',1,'SYS','0.0.0.0','prueba@pruebas.com',1,0,0,100,1,0,0,1,1,0,0,0) ";
    public static final String InsertUser = "INSERT INTO Users (Nick,Name,Password,Level,OrdersAccess,MovsAccess,ProdsAccess,Clients,POS,Loged,Discount,PricesList,PurchasesAccess) values ('SUP','Usuario Supervisor','SUP','Administrador',1,1,1,1,0,0,0,0,1) ";
}